name=Soldered LCD Arduino Librray
version=1.0.1
author=Soldered
maintainer=Soldered <soldered@soldered.com>
sentence=Library for 16x2 and 20x4 EasyC LCD displays 
paragraph=This adapter makes connection of LCD to Dasduino (or any other Arduino-compatible board) a breeze! It uses I2C communication which needs only two pins. It can be used and work with all of ours LCDs (16x2, 20x4, 16x4)
category=Display
url=https://solde.red/333003
repository=https://github.com/SolderedElectronics/Soldered-16x2-LCD-Arduino-Library
architectures=*
includes=LCD-SOLDERED.h
